# Generated by Django 3.1.4 on 2021-02-22 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='unkown', max_length=100, verbose_name='username'),
        ),
    ]
