# Generated by Django 3.1.4 on 2021-03-11 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='name',
            field=models.TextField(default='User Account', max_length=20),
            preserve_default=False,
        ),
    ]
