# Generated by Django 3.1.4 on 2021-03-10 01:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_auto_20210202_2058'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash_amount', models.FloatField()),
                ('equity_amount', models.FloatField()),
                ('option_amount', models.FloatField()),
                ('short_equity_amount', models.FloatField()),
                ('short_option_amount', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='optionposition',
            name='parent_trade',
        ),
        migrations.RemoveField(
            model_name='order',
            name='linking_position',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='trader',
        ),
        migrations.DeleteModel(
            name='EquityPosition',
        ),
        migrations.DeleteModel(
            name='OptionPosition',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Trade',
        ),
        migrations.AddField(
            model_name='position',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acct_positions', to='main.account'),
        ),
    ]
