# Generated by Django 3.1.4 on 2021-03-11 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trade_accounts', '0001_initial'),
        ('main', '0003_auto_20210309_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acct_positions', to='trade_accounts.account'),
        ),
        migrations.DeleteModel(
            name='Account',
        ),
    ]
